### ISSUE TITLE
Not receiving notifications

### ISSUE THREAD

**Issue by maxp-edcast** [olsh/Feedly-Notifier#113]
I see 576 unread articles but never got the request for desktop notification permission. It doesn't show any notifications. Chrome 62.0 on OSX 10.12

**Comment by olsh** [comment]
Hi @maxp-edcast,

Thank you for the reporting.

> I see 576 unread articles but never got the request for desktop notification permission.

You should get the permission request on the extension installation.

Could you please check if there are errors on the background page? 
In order to do this, you have to go to `chrome://extensions/`, check `developer mode` checkbox and open `background page` link of the extension.
