### ISSUE TITLE
Possible XSS

### ISSUE THREAD

**Issue by radimsuckr** [olsh/Feedly-Notifier#162]
**Describe the bug**
[This article](https://www.vzhurudolu.cz/prirucka/js-moduly) just showed up in my Feedly and the part `<script type="module">` of the title didn't show up in the extension. Only the ending question mark was shown.

**To Reproduce**
1. Have 'https://www.vzhurudolu.cz/prirucka/js-moduly' show up in the extension
2. The part of JS code does not show up in the extension

**Expected behavior**
`<script type="module">` is visible in the title.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 74.0

**Comment by olsh** [comment]
Hi @radimsuckr,

Thanks for the reporting 👍 

I just checked the RSS and it seems that feedly.com (not extension) removes the tag.
Here is the screenshot from feedly.com

![image](https://user-images.githubusercontent.com/3613592/78080476-ff23cd80-73b6-11ea-9155-f1b3c35bc8ba.png)

**Comment by radimsuckr** [comment]
Hi @olsh, I'm happy to hear that's not a security vulnerability.

I think we can close this since "the mystery" is solved. Thank you!

**Comment by olsh** [comment]
Yes, we are safe here.
https://developer.feedly.com/v3/entries/
According to Feedly API

> title
Optional string the article’s title. This string does not contain any HTML markup.

Moreover, for Firefox, I do the following trick because otherwise, the extension doesn't pass the review.

https://github.com/olsh/Feedly-Notifier/blob/24aa46eed4615830698462a8c87fc156a4abed6b/src/scripts/popup.js#L124-L128
