### ISSUE TITLE
Doesn't login

### ISSUE THREAD

**Issue by sal-versij** [olsh/Feedly-Notifier#167]
**Describe the bug**
Even if the login in feedly.com goes successfully, the extension ask me to login, so I think that the extension isn't viewing that i alredy logged in(probably something changed in the site so now the extension doesn't know if I've alredy made the login)

**To Reproduce**
1. Open the pop-up of the extension
2. Click on login
3. I've done the login via google, so I don't know if for the direct login of feedly is different
4. The extension ask me to login even if I'me in the site alredy logged in

**Expected behavior**
That the extension would see that I'me logged in

**Desktop (please complete the following information):**
 - Windows 10 64bit
 - Chrome
 - Versione 83.0.4103.116 (Build ufficiale) (a 64 bit)

**Comment by shinodem** [comment]
The same here, it redirect on main page that's all. 
And android app many months won't open just widget working.

**Comment by olsh** [comment]
Hi @sal-versij, @shinodem 

Thank you for letting me know.
Have you tried to remove and install the extension? Could you please check the console output?

@shinodem 
Please note, that the repo contains only browser extensions, there is no android app.

**Comment by shinodem** [comment]
Hi,
Yes reinstalling extension works again.

**Comment by olsh** [comment]
The bug was probably fixed in 2.25.0 version that is on the review now.

**Comment by RichDG** [comment]
Hi. I for reasons I won't bore you with here I have to use an old version of Firefox (47.0.1) and consequently an old version of Feedly Notifier (2.11.2). All worked fine until the latest update and now I cannot log in any more. Is there a way to get this old version and try re-installing it (web search says no version this old available) or another way to get the authentication to log in to my account and retrieve my feeds ? Thanks for any help and a great app (even though I have a feeling the answer will be no and I can no longer use it). My pc is windows 10 home 64-bit and fully updated bar the last March update that cannot be installed yet due to conflicts.

**Comment by GAJansen** [comment]
After this add-on was autoupdated to version 2.24.4 in Vivaldi, I encountered the 'login-bug' too. 

Removing and reinstalling as suggested by @olsh has solved the issue, allthough I am still in running version 2.24.4 (2.25.0 is apparently still in review)

**Comment by olsh** [comment]
Version 2.25.0 was published in all stores.
Feel free to open the issue if the login doesn't work for you.
