### ISSUE TITLE
Sorting problem

### ISSUE THREAD

**Issue by Mioni** [olsh/Feedly-Notifier#224]
Hello, I use engagement rate mode but it is not working, there is an article that has more popularity but is below that has less popularity.
![image](https://user-images.githubusercontent.com/6830783/194564040-2d127e00-9589-4e1f-b22a-55c2d48ffc34.png)

**Comment by olsh** [comment]
Hi @Mioni 

Thank you for the feedback 👍🏻 

This may sound strange, but this is by design 😟 
The plugin performs sorting as Feedly does. It uses `engagementRate` for sorting, not `engagement`.
https://github.com/olsh/Feedly-Notifier/blob/9fb5d6be181995d3c02e9dbeae518fc421dcc461/src/scripts/core.js#L605-L611


Here is the response from the Feedly team:
>   The sorting is done on `engagementRate`, not `engagement`. This normalizes the engagement values between entries and between sources, so that very popular sources don't push smaller ones out of the results. It also uses a recent time window first, and loads older entries if it doesn't find enough, so the results might vary.

Feel free to re-open the issue.

**Comment by Mioni** [comment]
Wouldn't there be a way for the extension to sort the most popular articles? like this extension does? https://github.com/soufianesakhi/feedly-filtering-and-sorting

**Comment by olsh** [comment]
Well, we could sort by the `engagement` property on the client, but this won't solve the problem with sorting on the server side.
The extension requests only top `n` (Max number of feeds in the popup) articles from the Feedly API. And Feedly API sorts by the `engagementRate` anyway.
