### ISSUE TITLE
Would you provide the "font change" option?

### ISSUE THREAD

**Issue by devolition** [olsh/Feedly-Notifier#45]
Hi. I'm Korean. and thanks for add-on "Feedly Notifier"

but while I use this add-on. I have a few discomforts.
Current base font of add-on for alphabet, but In Korean letter... have bad readability. 
like Comic Sans at alphabet font.

so.. would you add the font change option ?
OR change the korean font like "Google Noto Sans CJK KR" or others?

![2015-10-05 12 48 00](https://cloud.githubusercontent.com/assets/14971007/10272740/63164d82-6b5f-11e5-8188-0013916f7fda.JPEG)

**Comment by devolition** [comment]
thanks. Very Very GOOD!

**Comment by olsh** [comment]
You're welcome.

**Comment by soya-daizu** [comment]
@olsh
Sorry for the necro, but bundling and manually specifying a region-specific font is not the solution for this problem.
Noto Sans CJK family comes with different variants depending on the target region (JP, KR, SC, TC, and HW), because a lot of ideographs in these languages share the same code point but has a slightly different shape depending on the region.

The font bundled with Feedly Notifier is a Korean variant of the Noto Sans CJK family, meaning that characters that are shared in Chinese, Japanese, and Korean are all displayed in Korean variant which is not suitable in Chinese and Japanese sentences.

The original problem was that latin characters were displayed in sans-serif typeface while characters not included in Open Sans are displayed in serif typeface. The solution for this problem is to simply replace fallback typeface to sans-serif from serif.

```diff
#feed-empty,
.title {
    color: var(--item-title-color);

-    font-family: "Open Sans Condensed", "Noto Sans KR", serif;
+    font-family: "Open Sans Condensed", sans-serif;
}
```

Any major operating systems already has a good default typeface for their languages, so it's best to let them use whatever they have on their platform when the character doesn't exist in our preferred typeface (in this case, which seems like Open Sans Condensed).

**Comment by olsh** [comment]
Hi @soya-daizu,

Thank you for the detailed explanation. 🔝 
If I understand you suggestion correctly, this will lead us to the initial state (on the topicstarter sceencap https://github.com/olsh/Feedly-Notifier/issues/45#issue-109726658 )? Please correct me if I'm wrong.

Here are two screenshots on my Windows 10 with the latest updates
With current code
![1](https://user-images.githubusercontent.com/3613592/195936925-76327c10-0595-4a4b-bedc-1fa9dea132f9.png)

With your fix
![2](https://user-images.githubusercontent.com/3613592/195936934-1be7ed89-619a-4602-922a-124c2be7ef8c.png)

Probably my system doesn't have the required fonts installed.

Also, I'll gladly accept a PR for this.

**Comment by soya-daizu** [comment]
> Probably my system doesn't have the required fonts installed.

It seems like your system does have some sans-serif font that can display Korean scripts, but in a limited set of weight so it looks odd when combined with bold latin scripts.

I can only check the behavior in macOS and Manjaro Linux, and macOS already comes with good region-specific fonts with various weights regardless of locale settings. For example, there's "Apple SD Gothic Neo" for Korean, "Hiragino Sans" for Japanese, and "PingFang" for Chinese.

On Windows, it seems like any system fonts for languages not included in your system locale need to be installed manually through "Optional Features" in settings.
https://learn.microsoft.com/en-us/typography/fonts/windows_10_font_list
Looking at the list, anyone who has set their languages should have a good selection of fonts preinstalled, and it should be fallbacked properly.

**Comment by soya-daizu** [comment]
@olsh 
> Probably my system doesn't have the required fonts installed.

It seems like your system does have some sans-serif font that can display Korean scripts, but with a limited set of weight so it looks odd when combined with bold latin characters. It's a little different from the topic starter's screenshot because in his screenshot, all Korean scripts are displayed in serif typeface which itself isn't bad when serif script is intended, but not in combination with latin sans-serif scripts. But in your case, since we replaced the fallback font into sans-serif, they are at least all displayed in sans-serif typefaces. If you had the appropriate system fonts installed (which most CJK users do by default), it should look just as good without bundling a custom font.

I can only check the behavior in macOS and Manjaro Linux, but macOS already comes with good region-specific fonts with various weights regardless of locale settings. For example, there's "Apple SD Gothic Neo" for Korean, "Hiragino Sans" for Japanese, and "PingFang" for Chinese.
https://developer.apple.com/fonts/system-fonts/#preinstalled

On Windows, it seems like any system fonts for languages not included in the system locale need to be installed manually through "Optional Features" in the settings.
https://learn.microsoft.com/en-us/typography/fonts/windows_10_font_list
Looking at the list, anyone who has set their languages or installed these fonts afterward should get good fonts for their languages and they should get fallbacked properly.

I think I will make a PR for this later, thanks for checking!

**Comment by olsh** [comment]
> I think we need to add font-weight: 500; or something in addition to that.

You're right, `font-weight: 700;` looks much better in my opinion.

![image](https://user-images.githubusercontent.com/3613592/195973755-c4a716a5-88f4-4674-920b-ccb4b20ae00c.png)

> I can only check the behavior in macOS and Manjaro Linux

I can test it on Windows if you give me RSS feeds for testing.

**Comment by soya-daizu** [comment]
On my environment, setting the weight to 700 thickens the latin characters as well, but I was able work it around by adding font-weight specification to the @font-face as well.
![700_1](https://user-images.githubusercontent.com/18283756/196004991-09bf300c-fe5e-4ca8-b6f5-f5d6e7b58dc4.png)
![700_2](https://user-images.githubusercontent.com/18283756/196004994-1ad91bd8-bdae-4633-8a0a-726e693fdd6e.png)

**Comment by olsh** [comment]
@soya-daizu 
Thank you! 👍🏻 
Looks good, would you open a PR?

**Comment by soya-daizu** [comment]
Opened!
