### ISSUE TITLE
Notification badge is blue when Material Design top chrome is enabled

### ISSUE THREAD

**Issue by LastInLine** [olsh/Feedly-Notifier#49]
Chrome stable, version 49.0.2623.75 m, if the flag "Material design in the browser's top chrome" (#top-chrome-md) is enabled on Windows, the notification badge is blue rather than red.  The flag shrinks the icons significantly so it's difficult to read the unread count (I mention this because it may make sense to address both with the same fix).

**Comment by olsh** [comment]
@LastInLine Thank you for the report.
It seems like it's a Chrome problem, because other extensions have the same problem.
http://www.evernote.com/shard/s9/sh/ae35774f-9992-4d31-8db6-8cc2710a0811/26ce1df24cb2571eca72688dd02b34cf
Chrome doesn't provide much API to customize the icons, so I'm afraid we can't fix it now.

**Comment by LastInLine** [comment]
I'm not at work at the moment so I don't have access to a Windows computer, but I do know, and that screenshot shows, that for some reason some extensions get other colors.  I *think* I've seen one generate a red badge.

Perhaps a bug report needs to be filed with the Chromium project to address this?  I don't know enough about this to make a detailed report myself.  A quick search of the bugtracker did not prove fruitful in finding an existing bug (but did reveal many issues with the change to Material Design).

**Comment by olsh** [comment]
@LastInLine yes, you're right, Chrome [provides an API](https://developer.chrome.com/extensions/browserAction#method-setBadgeBackgroundColor) for setting the badge color. We get the blue color because we do not set the badge background explicitly.
So, yes, we can fix the color problem.

I just thought that the more annoying problem is the icons size and the font.

**Comment by LastInLine** [comment]
Hooray for the color!

Yeah, you're right the size is annoying and there is [a bug filed](https://bugs.chromium.org/p/chromium/issues/detail?id=546206&q=material&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&start=100) but you're right, there is nothing to do on that but wait.

**Comment by olsh** [comment]
Fixed in be9f7193ec228426ab9727e3d7722ccc49016d2c
