### ISSUE TITLE
Intermittently not updating properly

### ISSUE THREAD

**Issue by gri1n** [olsh/Feedly-Notifier#99]
Intermittently Feedly Notifier is not updating properly. The unread count on the icon gets stuck and won't change again until I log the extension out then back in again.

Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
Feedly Notifier 2.15.2

**Comment by olsh** [comment]
@gri1n are there any errors in the console?

**Comment by soeren-r** [comment]
jquery.min.js:2 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-65J4FkC69tsUQ2ue0zPaa9o7gcuO5GyseHj1aTC+UUA='), or a nonce ('nonce-...') is required to enable inline execution.

p @ jquery.min.js:2

**Comment by olsh** [comment]
Hi guys, sorry for the delay.

Could you please try the latest version 2.15.4?

**Comment by soeren-r** [comment]
Seems to work now, thank you
